site_name: SAGE Engine Docs
site_url: https://example.com
docs_dir: docs/en
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
nav:
  - Home: index.md
  - Reference:
      - Engine API: reference/engine.md
      - NanoCore FFI: reference/nano_core.md
