[project]
name = "sage_feather"
version = "0.1.0a0"
requires-python = ">=3.8"
dependencies = ["pyyaml", "lupa"]

[project.optional-dependencies]
dev = ["ruff", "pytest", "pyyaml", "lupa"]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "sage_engine",
    "sage_engine.core",
    "sage_engine.object",
    "sage_engine.dag",
    "sage_engine.render",
    "sage_engine.window",
    "sage_engine.resource",
    "sage_engine.ui",
    "sage_engine.profiling",
    "sage_engine.plugin",
    "sage_object",
    "sage_fs",
    "sage",
]

[tool.setuptools.package-data]
"sage_fs" = ["*.yaml", "flow_modules/*.yaml"]
"sage.config" = ["*.yaml"]
