[project]
name = "sage_engine"
version = "0.1.0a0"
requires-python = ">=3.8"
dependencies = ["typing-extensions", "pillow"]

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["sage_engine"]
