[project]
name = "sage_feather"
version = "0.1.0a0"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["sage_engine"]
