[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sage-engine"
version = "0.0.1-alpha"
description = "SAGE 2D game engine"
authors = [{name = "SAGE Team"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Games/Entertainment",
]
keywords = ["game", "engine", "sage"]
dependencies = [
    "Pillow",
]

[project.optional-dependencies]
opengl = ["PyQt6>=6.5", "PyOpenGL>=3.1"]
sdl = ["PySDL2"]
qt = ["PyQt6>=6.5"]
audio = ["pygame>=2.6"]

[project.urls]
Homepage = "https://github.com/AGamesStudios/SAGE-Engine"
Repository = "https://github.com/AGamesStudios/SAGE-Engine"
[project.scripts]
sage-editor = "sage_editor.app:main"
sage-runtime = "engine.runtime.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["engine*", "sage_editor*", "sage_paint*", "sage_sdk*"]
