[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sage-engine"
version = "0.0.1-alpha"
description = "SAGE 2D game engine with compact resource formats"
authors = [{name = "Amckinator Games Studios (AGStudios)", email = "amckinatorgames@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Games/Entertainment",
]
keywords = ["game", "engine", "sage", "sageaudio", "sagemesh"]
dependencies = [
    "Pillow",
    "tomli; python_version < '3.11'",
]

[project.optional-dependencies]
opengl = ["PyQt6>=6.5", "PyOpenGL>=3.1"]
sdl = ["PySDL2"]
qt = ["PyQt6>=6.5"]
audio = ["pygame>=2.6"]

[project.urls]
Homepage = "https://github.com/AGamesStudios/SAGE-Engine"
Repository = "https://github.com/AGamesStudios/SAGE-Engine"
[project.scripts]
sage-runtime = "engine.runtime.__main__:main"
sage-editor = "sage_editor:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["engine*", "sage_editor*"]

[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
reportMissingImports = false
reportMissingModuleSource = false
reportUnsupportedDunderAll = false
