# Minimal language dictionary for the engine.
LANGUAGES = {
    'English': {
        'KeyPressed': 'Key Pressed',
        'KeyReleased': 'Key Released',
        'MouseButton': 'Mouse Button',
        'InputState': 'Input State',
        'AfterTime': 'After Time',
        'Collision': 'Collision',
        'EveryFrame': 'Every Frame',
        'VariableCompare': 'Variable Compare',
        'Move': 'Move',
        'SetPosition': 'Set Position',
        'Destroy': 'Destroy',
        'Print': 'Print',
        'PlaySound': 'Play Sound',
        'Spawn': 'Spawn',
        'SetVariable': 'Set Variable',
        'ModifyVariable': 'Modify Variable',
        'SetZoom': 'Set Zoom',
        'ZoomAbove': 'Zoom Above',
    },
    'Русский': {
        'KeyPressed': 'Нажата клавиша',
        'KeyReleased': 'Клавиша отпущена',
        'MouseButton': 'Кнопка мыши',
        'InputState': 'Состояние ввода',
        'AfterTime': 'Через время',
        'Collision': 'Столкновение',
        'EveryFrame': 'Каждый кадр',
        'VariableCompare': 'Сравнение переменной',
        'Move': 'Переместить',
        'SetPosition': 'Установить позицию',
        'Destroy': 'Удалить',
        'Print': 'Вывести текст',
        'PlaySound': 'Проиграть звук',
        'Spawn': 'Создать объект',
        'SetVariable': 'Задать переменную',
        'ModifyVariable': 'Изменить переменную',
        'SetZoom': 'Установить зум',
        'ZoomAbove': 'Зум больше',
    },
}
