# Minimal language dictionary for the engine.
LANGUAGES = {
    'English': {
        'KeyPressed': 'Key Pressed',
        'KeyReleased': 'Key Released',
        'MouseButton': 'Mouse Button',
        'InputState': 'Input State',
        'Collision': 'Collision',
        'AfterTime': 'After Time',
        'EveryFrame': 'Every Frame',
        'VariableCompare': 'Variable Compare',
        'ZoomAbove': 'Zoom Above',
        'EventTriggered': 'Event Triggered',
        'InView': 'In View',
        'Move': 'Move',
        'SetPosition': 'Set Position',
        'Destroy': 'Destroy',
        'Print': 'Print',
        'PlaySound': 'Play Sound',
        'Spawn': 'Spawn',
        'SetVariable': 'Set Variable',
        'ModifyVariable': 'Modify Variable',
        'SetZoom': 'Set Zoom',
        'PanCamera': 'Pan Camera',
        'CenterCamera': 'Center Camera',
        'EnableEvent': 'Enable Event',
        'DisableEvent': 'Disable Event',
        'ResetEvent': 'Reset Event',
    },
    'Русский': {
        'KeyPressed': 'Нажата клавиша',
        'KeyReleased': 'Клавиша отпущена',
        'MouseButton': 'Кнопка мыши',
        'InputState': 'Состояние ввода',
        'Collision': 'Столкновение',
        'AfterTime': 'Через время',
        'EveryFrame': 'Каждый кадр',
        'VariableCompare': 'Сравнение переменной',
        'ZoomAbove': 'Зум больше',
        'EventTriggered': 'Событие сработало',
        'InView': 'В кадре',
        'Move': 'Переместить',
        'SetPosition': 'Установить позицию',
        'Destroy': 'Удалить',
        'Print': 'Вывести текст',
        'PlaySound': 'Проиграть звук',
        'Spawn': 'Создать объект',
        'SetVariable': 'Задать переменную',
        'ModifyVariable': 'Изменить переменную',
        'SetZoom': 'Установить зум',
        'PanCamera': 'Сдвинуть камеру',
        'CenterCamera': 'Центрировать камеру',
        'EnableEvent': 'Включить событие',
        'DisableEvent': 'Выключить событие',
        'ResetEvent': 'Сбросить событие',
    },
}
