LANGUAGES = {
    'English': {
        'file': 'File',
        'edit': 'Edit',
        'open': 'Open',
        'save': 'Save',
        'run': 'Run',
        'add_sprite': 'Add Sprite',
        'object': 'Object:',
        'add_variable': 'Add Variable',
        'conditions': 'Conditions',
        'actions': 'Actions',
        'add_condition': 'Add Condition',
        'add_action': 'Add Action',
        'console': 'Console',
        'viewport': 'Viewport',
        'logic': 'Logic',
        'name': 'Name',
        'value': 'Value',
        'add_event': 'Add Event',
        'open_scene': 'Open Scene',
        'save_scene': 'Save Scene',
        'browse': 'Browse',
        'image_files': 'Images (*.png *.jpg *.bmp)',
        'json_files': 'JSON Files (*.json)'
    },
    'Русский': {
        'file': 'Файл',
        'edit': 'Правка',
        'open': 'Открыть',
        'save': 'Сохранить',
        'run': 'Запуск',
        'add_sprite': 'Добавить спрайт',
        'object': 'Объект:',
        'add_variable': 'Добавить переменную',
        'conditions': 'Условия',
        'actions': 'Действия',
        'add_condition': 'Добавить условие',
        'add_action': 'Добавить действие',
        'console': 'Консоль',
        'viewport': 'Сцена',
        'logic': 'Логика',
        'name': 'Имя',
        'value': 'Значение',
        'add_event': 'Добавить событие',
        'open_scene': 'Открыть сцену',
        'save_scene': 'Сохранить сцену',
        'browse': 'Обзор',
        'image_files': 'Изображения (*.png *.jpg *.bmp)',
        'json_files': 'Файлы JSON (*.json)'
    }
}
DEFAULT_LANGUAGE = 'English'
