name: Generate Changelog
on:
  push:
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate changelog (standard-version)
        uses: conventional-changelog/standard-version-action@v3
        with:
          release-type: minor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
