
name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  smoke:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .
          python -m pip install glfw PyOpenGL pysdl2 pysdl2-dll
      - name: Linux XVFB
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb libglu1-mesa
      - name: Smoke tests
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a python scripts/smoke_tests.py
          else
            python scripts/smoke_tests.py
